DO $$
BEGIN
  PERFORM fn_assert_string('DEST_READUSER', '${DEST_READUSER}');

  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DEST_READUSER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DEST_READUSER};

  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${DEST_READUSER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${DEST_READUSER};
END
$$
