#!/usr/bin/env bash

#
# s3 files to copy to import for testing - tested this fro channel, and copies okay.
# try for all others Tuesday
#

aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Hierarchy-20170530-501.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Hierarchy-20170530-501.psv
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Statuses-20170604-3.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Statuses-20170604-3.psv
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Channel-20170530-501.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Channel-20170530-501.psv 
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Product-201705241257-26.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Product-201705241257-26.psv
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Geography-201706161045-3.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Geography-201706161045-3.psv
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-Hierarchy-20170530-501.psv s3://ra-md-poc-dcuk039/import/FREEHUB-Hierarchy-20170530-501.psv
aws s3 cp s3://ra-md-poc-dcuk039/processed/FREEHUB-ProductSeasonality-201705241257-4.psv s3://ra-md-poc-dcuk039/import/FREEHUB-ProductSeasonality-201705241257-4.psv

