CREATE TABLE IF NOT EXISTS conformed.dim_date (
    dim_date_id int4 not null,
    day_sequence_number int4 not null,
    week_sequence_number_usa int4 not null,
    month_sequence_number int2 not null,
    year_week_number int4,
    calendar_date date,
    is_weekday7_usa bool,
    is_weekday7_eu bool,
    calendar_date_eu char(10),
    calendar_date_usa char(10),
    calendar_day_of_month int4,
    day_with_suffix varchar(6),
    calendar_month_number int4,
    calendar_month_name varchar(30),
    calendar_month_start_date date,
    calendar_month_end_date date,
    calendar_year_month int4,
    calendar_week_number_usa int2,
    calendar_week_number_eu int2,
    calendar_continuum_year_week_number_usa int4,
    calendar_continuum_year_week_number_eu int4,
    calendar_continuum_year_week_number_usa_start_date date,
    calendar_continuum_year_week_number_usa_end_date date,
    calendar_continuum_year_week_number_eu_start_date date,
    calendar_continuum_year_week_number_eu_end_date date,
    calendar_iso_week_number int4,
    calendar_continuum_year_iso_week_number int4,
    calendar_continuum_year_iso_week_number_start_date date,
    calendar_continuum_year_iso_week_number_end_date date,
    week_day_number_usa int2,
    week_day_number_eu int2,
    week_day_name varchar(30),
    calendar_quarter_name varchar(6),
    calendar_quarter_number int2,
    calendar_quarter_day_number int4,
    calendar_quarter_month_number int4,
    calendar_quarter_start_date date,
    calendar_quarter_end_date date,
    calendar_year int4,
    calendar_year_start_date date,
    calendar_year_end_date date,
    PRIMARY KEY (dim_date_id)
);