CREATE TABLE IF NOT EXISTS sales.fact_weekly_sales_basic
(
    batch_id numeric(10, 0) not null default 1,
    dim_date_id int8 not null default 1,
    dim_retailer_id int8 not null,
    dim_product_id int8 not null,
    dim_geography_id int8 not null,
    dim_currency_id int8 not null,
    dim_seasonality_id int8 not null,
    dim_junk_id int8 not null,
    dim_price_status_id int8 not null,
    dim_channel_id int8 not null,
    scanned_margin float8,
    clearance_sales_value float8,
    clearance_sales_quantity float8,
    promotion_sales_value float8,
    promotion_sales_quantity float8,
    store_stock_value_no_negatives float8,
    store_stock_volume_no_negatives float8,
    markdown_price float8,
    full_price float8,
    provided_csp float8,
    provided_osp float8,
    current_selling_price float8,
    original_selling_price float8,
    cost_price float8,
    store_stock_value float8,
    store_stock_volume float8,
    depot_stock_value float8,
    depot_stock_volume float8,
    depot_stock_cost float8,
    sit_stock_cost float8,
    commitment_cost float8,
    vat float8,
    sales_value float8,
    sales_volume float8,
    intake_plus_future_commitment_volume float8,
    intake_plus_future_commitment_value float8,
    total_stock_value float8,
    total_stock_volume float8,
    markdown_cost float8,
    optimisation_csp float8,
    optimisation_osp float8,
    PRIMARY KEY (dim_date_id, dim_product_id, dim_geography_id, dim_seasonality_id, dim_channel_id),
    FOREIGN KEY (dim_date_id) REFERENCES conformed.dim_date (dim_date_id),
    FOREIGN KEY (dim_retailer_id) REFERENCES conformed.dim_retailer (dim_retailer_id),
    FOREIGN KEY (dim_product_id) REFERENCES conformed.dim_product (dim_product_id),
    FOREIGN KEY (dim_geography_id) REFERENCES conformed.dim_geography (dim_geography_id),
    FOREIGN KEY (dim_currency_id) REFERENCES conformed.dim_currency (dim_currency_id),
    FOREIGN KEY (dim_seasonality_id) REFERENCES conformed.dim_seasonality (dim_seasonality_id),
    FOREIGN KEY (dim_junk_id) REFERENCES sales.dim_junk (dim_junk_id),
    FOREIGN KEY (dim_price_status_id) REFERENCES markdown.dim_price_status (dim_price_status_id),
    FOREIGN KEY (dim_channel_id) REFERENCES conformed.dim_channel (dim_channel_id)
);