drop table if exists stage.sales;

create table stage.sales (
    batch_id int,
    dim_retailer_id int,
    reporting_date varchar(10),
    reporting_date_period_type char(1),
    geography_type_key char(1),
    geography_key varchar(20),
    product_key1 varchar(20),
    product_key2 varchar(20),
    product_key3 varchar(20),
    product_key4 varchar(20),
    product_status_key varchar(20),
    channel_key varchar(20),
    year_seasonality_key varchar(20),
    iso_currency_code varchar(3),
    stock_value numeric(20, 2),
    stock_quantity int,
    stock_cost numeric(20, 2),
    price_status_key char(1),
    scanned_margin numeric(20, 2),
    sales_value numeric(20, 2),
    sales_quantity int,
    sales_cost numeric(20, 2),
    clearance_sales_value numeric(20, 2),
    clearance_sales_quantity int,
    promotion_sales_value numeric(20, 2),
    promotion_sales_quantity int,
    system_price numeric(20, 2),
    selling_price numeric(20, 2),
    stores_with_stock int,
    stores_with_sales int,
    markdown_value numeric(20, 2),
    full_price_adjustment_value numeric(20, 2),
    realised_markdown_value numeric(20, 2),
    promo_markdown_value numeric(20, 2),
    row_id bigint identity(1,1) not null
);