CREATE TABLE IF NOT EXISTS sales.fact_weekly_sales_initial
(
	batch_id int NOT NULL,
	dim_date_id int NOT NULL,
	dim_retailer_id bigint NOT NULL,
	dim_product_id bigint NOT NULL,
	dim_geography_id int NOT NULL,
	dim_currency_id int NOT NULL,
	dim_seasonality_id int NOT NULL,
	dim_price_status_id int NOT NULL,
	dim_channel_id int NOT NULL,
	stock_value float NULL,
	stock_quantity int NULL,
	scanned_margin float NULL,
	combined_sales_value float NULL,
	combined_sales_quantity int NULL,
	clearance_sales_value float NULL,
	clearance_sales_quantity int NULL,
	promotion_sales_value float NULL,
	promotion_sales_quantity int NULL,
	retail_price float NULL,
	selling_price float NULL,
    local_tax_rate float NULL,
	PRIMARY KEY (dim_date_id, dim_product_id, dim_geography_id, dim_seasonality_id, dim_channel_id),
	FOREIGN KEY (dim_date_id) REFERENCES conformed.dim_date (dim_date_id),
	FOREIGN KEY (dim_retailer_id) REFERENCES conformed.dim_retailer (dim_retailer_id),
	FOREIGN KEY (dim_product_id) REFERENCES conformed.dim_product (dim_product_id),
	FOREIGN KEY (dim_geography_id) REFERENCES conformed.dim_geography (dim_geography_id),
	FOREIGN KEY (dim_currency_id) REFERENCES conformed.dim_currency (dim_currency_id),
	FOREIGN KEY (dim_seasonality_id) REFERENCES conformed.dim_seasonality (dim_seasonality_id),
	FOREIGN KEY (dim_price_status_id) REFERENCES markdown.dim_price_status (dim_price_status_id),
	FOREIGN KEY (dim_channel_id) REFERENCES conformed.dim_channel (dim_channel_id)
);